'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowRight, ArrowDown, Mail, Menu, X, Code2, Braces, Cpu, Workflow, GraduationCap, Award, ChevronDown, Copy, Check } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { links, projects, skillGroups, type Project } from '@/lib/portfolio';

const Github = Code2;
function Linkedin({size=18}:{size?:number}){return <span aria-hidden="true" style={{fontWeight:700,fontSize:size,lineHeight:1,letterSpacing:'-.06em'}}>in</span>}
function External({href,children,className=''}:{href:string;children:React.ReactNode;className?:string}) {return <a href={href} target={href.startsWith('mailto:')?undefined:'_blank'} rel="noopener noreferrer" className={className}>{children}</a>}
function Network(){
 const nodes=Array.from({length:32},(_,i)=>{const a=i*2.39996; const r=35+Math.sqrt(i/32)*145;return {x:220+Math.cos(a)*r,y:205+Math.sin(a)*r*.78}});
 return <div className="network" aria-hidden="true"><div className="network-label"><span className="tiny-dot"/> INTELLIGENCE, CONNECTED</div><svg viewBox="0 0 440 410"><defs><radialGradient id="halo"><stop stopColor="#548aff" stopOpacity=".2"/><stop offset="1" stopColor="#548aff" stopOpacity="0"/></radialGradient></defs><circle cx="220" cy="205" r="195" fill="url(#halo)"/><g className="network-spin">{nodes.map((n,i)=><g key={i}><line x1={n.x} y1={n.y} x2={nodes[(i+7)%32].x} y2={nodes[(i+7)%32].y} stroke="#6488b9" strokeOpacity=".24"/><line x1={n.x} y1={n.y} x2={220} y2={205} stroke="#6693d5" strokeOpacity=".13"/><circle cx={n.x} cy={n.y} r={i%5===0?3.6:2} fill={i%3===0?'#c8ddff':'#5c8beb'} className="node" style={{animationDelay:`${i*.18}s`}}/></g>)}</g><circle cx="220" cy="205" r="41" fill="#101c31" stroke="#476bab"/><path d="M210 194l-11 11 11 11m20-22 11 11-11 11m-7-28-6 36" fill="none" stroke="#c4daff" strokeWidth="2"/></svg><span className="net-tag tag-data">01 · DATA</span><span className="net-tag tag-models">02 · MODELS</span><span className="net-tag tag-systems">03 · SYSTEMS</span><div className="network-bottom">INPUT → REASON → BUILD</div></div>
}
function Counter({value,suffix=''}:{value:number;suffix?:string}){const ref=useRef<HTMLSpanElement>(null);const [shown,setShown]=useState(value);useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;let raf=0;const o=new IntersectionObserver(([e])=>{if(!e.isIntersecting)return;const start=performance.now();const tick=(t:number)=>{const p=Math.min((t-start)/850,1);setShown(Math.round(value*(1-Math.pow(1-p,3))));if(p<1)raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);o.disconnect()});if(ref.current)o.observe(ref.current);return()=>{o.disconnect();cancelAnimationFrame(raf)}},[value]);return <span ref={ref}>{shown}{suffix}</span>}
function ProjectVisual({id}:{id:string}) {
 if(id==='codesync')return <div className="visual code-visual"><div className="mock-caption">CONCEPTUAL INTERFACE</div><div className="editor"><div className="editor-top"><Braces size={16}/><span>CodeSync</span><span className="room">room / build-together</span><span className="avatars">SV<span>+</span></span></div><div className="editor-tab">〈〉 collaboration.js</div><pre><span className="ln">01</span> <span className="purple">const</span> room = <span className="blue">createRoom</span>();{'\n'}<span className="ln">02</span>{'\n'}<span className="ln">03</span> <span className="purple">function</span> <span className="blue">buildTogether</span>() {'{'}{'\n'}<span className="ln">04</span>   room.<span className="blue">on</span>(<span className="green">'code:change'</span>,{'\n'}<span className="ln">05</span>     (code) =&gt; <span className="blue">sync</span>(code));{'\n'}<span className="ln">06</span> {'}'}<span className="code-cursor"/></pre><div className="editor-footer"><span className="tiny-dot"/> Connected <span>JavaScript · UTF-8</span></div></div></div>;
 if(id==='whispr')return <div className="visual whispr-visual"><div className="mock-caption">CONCEPTUAL INTERFACE</div><div className="whispr-window"><div className="whispr-brand">w<span>h</span>ispr.</div><p>A little mystery.<br/>A real connection.</p><div className="message-bubble">What’s something you could talk about for hours?</div><div className="message-bubble reply">Probably the idea I’m building next.</div><div className="whispr-state">ANONYMOUS BY DESIGN</div></div></div>;
 if(id==='forecast')return <div className="visual chart-visual"><div className="chart-top"><span>BEST RECORDED · LIGHTGBM</span><strong>0.9195 <small>R²</small></strong></div><svg viewBox="0 0 480 125" role="img" aria-label="Illustrative demand trend, not measured predictions"><path d="M0 25H480 M0 65H480 M0 105H480" stroke="#24313d" strokeDasharray="3 6"/><path d="M0 98L20 92 40 105 60 70 80 82 100 48 120 60 140 94 160 66 180 72 200 32 220 54 240 64 260 28 280 45 300 38 320 74 340 48 360 60 380 18 400 40 420 14 440 31 460 19 480 25" fill="none" stroke="#77bba7" strokeWidth="2.5"/><path d="M0 105L20 100 40 94 60 80 80 75 100 59 120 67 140 87 160 74 180 62 200 43 220 47 240 57 260 36 280 39 300 49 320 63 340 58 360 47 380 30 400 33 420 24 440 27 460 28 480 19" fill="none" stroke="#819ed8" strokeWidth="2" strokeDasharray="5 5"/></svg><div className="chart-bottom"><span>MAE 0.0285</span><span>Illustrative trend · not evaluation data</span></div></div>;
 if(id==='car')return <div className="visual car-visual"><span className="mono">XGBOOST REGRESSION</span><div className="metric">0.919<span>R² ≈</span></div><div className="pipeline"><span>DATA</span><ArrowRight size={14}/><span>FEATURES</span><ArrowRight size={14}/><span>PREDICTION</span></div></div>;
 if(id==='translation')return <div className="visual translate-visual"><div><span>INPUT SEQUENCE</span><strong>Tokens → Embeddings</strong></div><div className="translation-line"><span>Encoder</span><ArrowRight/><span>Decoder</span></div><div><span>OUTPUT SEQUENCE</span><strong>Language, translated.</strong></div></div>;
 return <div className="visual forge-visual"><div className="mono">PROPOSED ARCHITECTURE</div><div className="forge-flow"><span>PDF</span><ArrowRight size={16}/><span>Embeddings</span><ArrowRight size={16}/><span>RAG</span></div><div className="forge-agent"><Workflow size={21}/> AI agents</div><div className="forge-outputs"><span>Explain</span><span>Quiz</span><span>Explore</span></div></div>;
}
function ProjectCard({project:p}:{project:Project}){return <article className={`project project-${p.id} reveal`}><ProjectVisual id={p.id}/><div className="project-copy"><div className="project-eyebrow">{p.category}{p.status&&<span className="status-pill">{p.status}</span>}</div><h3>{p.name}</h3><h4>{p.subtitle}</h4><p>{p.description}</p><div className="tags">{p.stack.map(t=><span key={t}>{t}</span>)}</div><details><summary>Explore the build <ChevronDown size={16}/></summary><div className="project-details"><p>{p.highlight}</p><ul>{p.features.map(f=><li key={f}>{f}</li>)}</ul></div></details><div className="project-links">{p.github?<External href={p.github}><Github size={16}/> Source code <ArrowUpRight size={15}/></External>:<span className="unavailable">Repository link pending</span>}{p.demo&&<External href={p.demo}>Live demo <ArrowUpRight size={15}/></External>}</div></div></article>}
const nav=['Home','About','Projects','Skills','Achievements','Contact'];
export default function Home(){
 const [menu,setMenu]=useState(false);const [active,setActive]=useState('home');const [scrolled,setScrolled]=useState(false);const [copied,setCopied]=useState(false);const cursor=useRef<HTMLDivElement>(null);const hero=useRef<HTMLElement>(null);
 useEffect(()=>{const scroll=()=>setScrolled(window.scrollY>40);window.addEventListener('scroll',scroll,{passive:true});const reveals=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');reveals.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>reveals.observe(el));const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)setActive(e.target.id)}),{rootMargin:'-15% 0px -65% 0px'});document.querySelectorAll('main section[id]').forEach(el=>observer.observe(el));const move=(e:PointerEvent)=>{if(matchMedia('(pointer: coarse), (prefers-reduced-motion: reduce)').matches)return;if(cursor.current){cursor.current.style.transform=`translate(${e.clientX}px,${e.clientY}px)`;cursor.current.classList.toggle('hovering',!!(e.target as HTMLElement).closest('a,button,summary'))}if(hero.current){hero.current.style.setProperty('--mx',`${(e.clientX/window.innerWidth-.5)*12}px`);hero.current.style.setProperty('--my',`${(e.clientY/window.innerHeight-.5)*12}px`)}};window.addEventListener('pointermove',move,{passive:true});return()=>{window.removeEventListener('scroll',scroll);window.removeEventListener('pointermove',move);reveals.disconnect();observer.disconnect()}},[]);
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setMenu(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[]);
 async function copyEmail(){try{await navigator.clipboard.writeText('sankalpv1904@gmail.com');setCopied(true);setTimeout(()=>setCopied(false),2400)}catch{window.location.href=links.email}}
 return <><a className="skip-link" href="#main">Skip to content</a><div className="cursor-ring" ref={cursor}/><header className={scrolled?'site-header compact':'site-header'}><a className="brand" href="#home" onClick={()=>setMenu(false)} aria-label="Sankalp Vats home"><span className="monogram">sv<span>.</span></span><span>Sankalp Vats</span></a><nav aria-label="Main navigation" className={menu?'nav open':'nav'} id="main-navigation">{nav.map(n=><a key={n} href={`#${n.toLowerCase()}`} aria-current={active===n.toLowerCase()?'location':undefined} onClick={()=>setMenu(false)}>{n}</a>)}</nav><a className="resume-nav" href="/Sankalp-Vats-Resume.pdf" download="Sankalp-Vats-Resume.pdf">Resume ↓</a><button className="menu-toggle" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} aria-controls="main-navigation" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
 <main id="main"><section className="hero shell" id="home" ref={hero}><div className="hero-main"><div className="eyebrow"><span className="eyebrow-line"/> IIT (BHU) <span> / </span> AI/ML <span> / </span> SOFTWARE</div><h1>Engineering ideas<br/>into <span>intelligent<br className="desktop-break"/> systems.</span></h1><p className="hero-intro">I’m <strong>Sankalp Vats</strong> — an IIT (BHU) student building at the intersection of Artificial Intelligence, Machine Learning and Software Engineering.</p><div className="hero-buttons"><a className="button primary" href="#projects">View my work <ArrowUpRight size={19}/></a><a className="button secondary" href="/Sankalp-Vats-Resume.pdf" download="Sankalp-Vats-Resume.pdf">Download resume <ArrowDown size={16}/></a></div><div className="hero-socials"><External href={links.github}><Github size={17}/> GitHub <ArrowUpRight size={13}/></External><External href={links.linkedin}><Linkedin size={17}/> LinkedIn <ArrowUpRight size={13}/></External><span className="profile-pending">LeetCode / Codeforces · links pending</span></div></div><div className="hero-aside"><Network/><div className="system-panel"><div><span className="mono">SYSTEM STATUS</span><span className="system-online"><i/> ONLINE</span></div><dl><div><dt>FOCUS</dt><dd>AI / ML + Software</dd></div><div><dt>EXPLORING</dt><dd>Agents & Reinforcement Learning</dd></div><div><dt>LOCATION</dt><dd>IIT (BHU), Varanasi</dd></div></dl></div></div><div className="hero-bottom"><span><i/> Currently exploring AI Agents & Reinforcement Learning</span><a href="#projects">SCROLL TO EXPLORE <ArrowDown size={14}/></a></div></section>
 <div className="stats shell reveal"><div><strong>8.80</strong><span>CPI / IIT (BHU)</span></div><div><strong><Counter value={419} suffix="+"/></strong><span>LeetCode problems</span></div><div><strong><Counter value={1430}/></strong><span>Codeforces peak</span></div><div><strong><Counter value={2028}/></strong><span>Expected graduation</span></div></div>
 <section id="projects" className="section shell"><div className="section-heading reveal"><div><div className="eyebrow">01 / SELECTED WORK</div><h2>Ideas, made real<span>.</span></h2></div><p>From real-time collaboration to predictive models.<br/>A selection of things I’ve been building.</p></div><div className="projects-grid">{projects.map(p=><ProjectCard key={p.id} project={p}/>)}</div><div className="projects-end"><span>Always learning. Always building.</span><External href={links.github} className="text-link">View all projects on GitHub <ArrowUpRight size={18}/></External></div></section>
 <section id="about" className="section about-section"><div className="shell about-grid"><div className="reveal"><div className="eyebrow">02 / THE PERSON BEHIND THE CODE</div><h2>An engineer.<br/>A builder.<br/><span>A curious mind.</span></h2><div className="about-location"><GraduationCap size={21}/><div>IIT (BHU), Varanasi<span>B.Tech. Chemical Engineering · Class of 2028</span></div></div></div><div className="about-copy reveal"><p className="large-copy">My degree is in Chemical Engineering.<br/>My curiosity takes me into code.</p><p>I’m a Chemical Engineering undergraduate at IIT (BHU) Varanasi with a strong interest in software development, machine learning and artificial intelligence.</p><p>I enjoy taking ideas from concept to implementation — designing systems, building APIs, training models and developing interfaces that turn experiments into working products.</p><p>Today, I’m focused on reinforcement learning, AI agents, RAG systems and full-stack development.</p></div><div className="journey reveal"><div className="mono">THE JOURNEY SO FAR</div><ol>{['Chemical Engineering','Programming','Competitive Programming','Machine Learning','Deep Learning','Full Stack','AI Agents & RL'].map((s,i)=><li key={s}><span>{String(i+1).padStart(2,'0')}</span>{s}</li>)}</ol></div></div></section>
 <section id="skills" className="section shell"><div className="section-heading reveal"><div><div className="eyebrow">03 / MY TOOLKIT</div><h2>The tools behind<br/>the thinking<span>.</span></h2></div><p>A growing toolkit for turning problems<br/>into systems that work.</p></div><Tabs defaultValue="Programming" className="skill-tabs reveal"><TabsList aria-label="Skill categories" className="skill-tabs-list">{Object.keys(skillGroups).map(g=><TabsTrigger key={g} value={g}>{g}</TabsTrigger>)}</TabsList>{Object.entries(skillGroups).map(([g,skills])=><TabsContent value={g} key={g}><div className="skills-panel"><div className="skills-title"><Code2 size={29}/><h3>{g}</h3><span>{skills.length} tools & concepts</span></div><div className="skill-items">{skills.map((s,i)=><div key={s}><span>{String(i+1).padStart(2,'0')}</span>{s}<ArrowUpRight size={15}/></div>)}</div></div></TabsContent>)}</Tabs></section>
 <section id="achievements" className="section shell"><div className="section-heading reveal"><div><div className="eyebrow">04 / PROBLEM SOLVING</div><h2>Logic. Practice. Progress<span>.</span></h2></div><p>Algorithms sharpen the way I think.<br/>Building puts that thinking to work.</p></div><div className="analytics-grid reveal"><div className="rating-card"><div className="rating-label"><Braces size={20}/> CODEFORCES</div><div className="rating-big">Specialist<span>1430 peak rating</span></div><div className="rating-divider"/><p><strong>~2300</strong> overall rank in a Div. 1 + Div. 2 contest</p><span className="small muted">Profile link not yet provided</span></div><div className="rating-card"><div className="rating-label"><Code2 size={20}/> LEETCODE</div><div className="rating-big"><Counter value={419} suffix="+"/><span>problems solved</span></div><div className="rating-divider"/><p><strong>1543</strong> contest rating <span className="muted">/ Top 33.65%</span></p><span className="small muted">Previously recorded statistics · profile link pending</span></div><div className="algorithm-card"><div className="mono">WAYS I APPROACH A PROBLEM</div><div className="tags">{['Data Structures','Algorithms','Dynamic Programming','Graphs','Binary Search','Segment Trees','Greedy','Recursion','Backtracking','Complexity Analysis'].map(t=><span key={t}>{t}</span>)}</div><div className="event"><Award size={24}/><p>CTRL + SHIFT + INTELLIGENCE<span>Participant · COPS Week ’25 · IIT (BHU)</span></p></div></div></div><p className="stats-note">Personal milestones supplied for this portfolio; these are not live platform statistics.</p></section>
 <section className="section shell credentials" aria-labelledby="education-heading"><div className="education reveal"><div className="eyebrow">05 / FOUNDATIONS</div><h2 id="education-heading">Education<span>.</span></h2><div className="education-item"><span className="timeline-dot"/><div className="mono">EXPECTED 2028</div><h3>IIT (BHU), Varanasi</h3><p>B.Tech. Chemical Engineering</p><span className="education-score">CPI 8.80</span></div><div className="education-item"><span className="timeline-dot"/><div className="mono">SCHOOL</div><h3>St. Francis School, Shamli</h3><div className="school-scores"><span>Class XII <strong>97%</strong></span><span>Class X <strong>97.5%</strong></span></div></div></div><div className="certifications reveal"><div className="eyebrow">CONTINUOUS LEARNING</div><h2>Beyond the classroom<span>.</span></h2>{[{name:'Deep Learning Specialization',detail:'Coursera'},{name:'Advanced Learning Algorithms',detail:'Coursera · June 11, 2025 · 34 hours',grade:'100%'},{name:'Supervised Machine Learning',detail:'Regression and Classification · Coursera',date:'March 24, 2025 · 33 hours',grade:'100%'}].map(c=><div className="certificate" key={c.name}><Award size={22}/><div><h3>{c.name}</h3><p>{c.detail}</p>{c.date&&<p>{c.date}</p>}</div>{c.grade&&<span>{c.grade}<small>GRADE</small></span>}</div>)}</div></section>
 <section className="section exploring"><div className="shell exploring-grid"><div className="reveal"><div className="eyebrow"><span className="tiny-dot"/> THE NEXT CHAPTER</div><h2>Currently<br/><span>exploring.</span></h2><p>I’m continuously learning by building. Right now I’m exploring how intelligent systems can reason, retrieve information, interact with tools and make sequential decisions.</p></div><div className="explore-nodes reveal">{[{icon:Cpu,name:'Reinforcement Learning',sub:'Decisions over time'},{icon:Workflow,name:'AI Agents & Multi-Agent Systems',sub:'Reasoning through tools'},{icon:Braces,name:'RAG Systems',sub:'Connecting knowledge to models'},{icon:Code2,name:'Advanced ML & System Design',sub:'From models to full-stack architecture'}].map(({icon:Icon,name,sub})=><div key={name}><Icon size={21}/><span>{name}<small>{sub}</small></span><span className="node-dot"/></div>)}</div></div></section>
 <div className="philosophy shell reveal"><div className="mono">A SIMPLE DEVELOPMENT PHILOSOPHY</div><p>Learn <span>→</span> Build <span>→</span> Break <span>→</span> Debug <span>→</span> <em>Improve.</em></p><div>Every project is an opportunity to turn theory into something tangible.</div></div>
 <section id="contact" className="contact-section shell reveal"><div className="eyebrow">06 / START A CONVERSATION</div><h2>Let’s build<br/><span>something.</span><ArrowUpRight aria-hidden="true"/></h2><p>Have an interesting idea, collaboration or internship opportunity?<br/>I’d love to hear from you.</p><div className="contact-email"><a href={links.email}>sankalpv1904@gmail.com <ArrowUpRight size={22}/></a><button onClick={copyEmail} aria-label={copied?'Email copied':'Copy email address'}>{copied?<Check size={19}/>:<Copy size={19}/>}</button><span role="status" className="copy-status">{copied?'Copied':''}</span></div><div className="contact-links"><External href={links.github}><Github size={18}/> GitHub <ArrowUpRight size={16}/></External><External href={links.linkedin}><Linkedin size={18}/> LinkedIn <ArrowUpRight size={16}/></External><a href={links.email}><Mail size={18}/> Email <ArrowUpRight size={16}/></a><a href="/Sankalp-Vats-Resume.pdf" download="Sankalp-Vats-Resume.pdf">Resume <ArrowDown size={16}/></a></div></section></main>
 <footer className="shell"><a href="#home" className="footer-brand">sv<span>.</span></a><div><strong>Sankalp Vats</strong><p>Building with code, learning with curiosity.</p></div><span>© 2026 Sankalp Vats</span><div className="footer-profiles"><External href={links.github}>GitHub</External><External href={links.linkedin}>LinkedIn</External><span>LeetCode · link pending</span><span>Codeforces · link pending</span><a href="/Sankalp-Vats-Resume.pdf" download="Sankalp-Vats-Resume.pdf">Resume ↓</a></div><a href="#home" className="back-top">Back to top <ArrowUpRight size={16}/></a></footer></>
}
