export const links = { github: 'https://github.com/sankalpvats', linkedin: 'https://www.linkedin.com/in/sankalp-vats-82432a321/', email: 'mailto:sankalpv1904@gmail.com' };
export type Project = { id: string; name: string; category: string; subtitle: string; description: string; stack: string[]; features: string[]; highlight: string; github?: string; demo?: string; status?: string };
export const projects: Project[] = [
 {id:'codesync',name:'CodeSync',category:'01 / REAL-TIME SYSTEMS',subtitle:'Great code starts with collaboration.',description:'A collaborative code editor that brings developers into shared rooms, keeping every keystroke in sync.',stack:['React','Node.js','Socket.IO','MongoDB'],features:['Real-time collaborative editing and room-based communication','User authentication, REST APIs and MongoDB integration','Instant code synchronization and join/leave handling'],highlight:'Built a real-time collaboration layer using WebSockets and Socket.IO.',github:'https://github.com/sankalpvats/CodeSync',demo:'https://code-sync.dev'},
 {id:'whispr',name:'Whispr',category:'02 / FULL-STACK DEVELOPMENT',subtitle:'Connection, with privacy built in.',description:'An anonymous matchmaking platform with secure authentication, thoughtful onboarding and a PostgreSQL-backed architecture.',stack:['Next.js','TypeScript','Prisma','PostgreSQL'],features:['Google Sign-In, phone OTP, JWT sessions and email verification','Protected API routes and multi-step onboarding','React Hook Form and Zod validation','Supabase, Firebase and Resend Email API'],highlight:'A full-stack authentication and onboarding architecture.',github:'https://github.com/sankalpvats/whispr-pp'},
 {id:'forecast',name:'Demand Forecasting',category:'03 / MACHINE LEARNING',subtitle:'Finding the signal in space and time.',description:'Spatiotemporal demand prediction across 1,249 geohashes, using six months of observations at 15-minute intervals.',stack:['LightGBM','XGBoost','CatBoost','Pandas'],features:['Latitude, longitude, hour and minute features','Cyclical hour_sin and hour_cos features','Geographic clustering across multiple services','Compared XGBoost, CatBoost and LightGBM'],highlight:'Best recorded LightGBM result: R² 0.9195 · MAE 0.0285.'},
 {id:'car',name:'Car Price Predictor',category:'04 / PREDICTIVE MODELLING',subtitle:'From vehicle data to price estimates.',description:'An XGBoost regression system that predicts automobile prices from vehicle specifications and historical data.',stack:['Python','XGBoost','NumPy','Scikit-learn'],features:['Data cleaning and exploratory data analysis','Feature engineering and model training','Hyperparameter tuning and prediction'],highlight:'Best recorded R² ≈ 0.919.',github:'https://github.com/sankalpvats/Car-Price-Predictor'},
 {id:'translation',name:'Neural Machine Translation',category:'05 / DEEP LEARNING',subtitle:'Learning to translate, sequence by sequence.',description:'An exploration of encoder-decoder architectures for sequence-to-sequence neural machine translation.',stack:['Python','TensorFlow / Keras','NLP','Seq2Seq'],features:['Tokenization, vocabulary creation and padding','Embeddings and encoder-decoder architecture','Sequence-to-sequence learning and BLEU evaluation'],highlight:'Exploring how neural networks represent language.'},
 {id:'studyforge',name:'StudyForge AI',category:'06 / AI SYSTEMS',subtitle:'Documents in. Understanding out.',description:'An AI study assistant designed to turn educational documents into explanations, questions, quizzes and structured study material.',stack:['RAG','Vector Database','Multi-Agent Systems'],features:['Planned pipeline: PDF processing → chunking → embeddings → vector database → RAG','Proposed research and explanation agents','Proposed question, quiz and report generation agents'],highlight:'Currently designing a multi-agent learning workflow.',status:'In development'}
];
export const skillGroups = {
 'Programming':['C++','Python','JavaScript','TypeScript','SQL','HTML','CSS'],
 'AI & ML':['Machine Learning','Deep Learning','NLP','Reinforcement Learning','RAG','AI Agents','Feature Engineering','Model Optimization'],
 'Frameworks':['PyTorch','TensorFlow','Keras','Scikit-learn','XGBoost','LightGBM','CatBoost','Pandas','NumPy'],
 'Full stack':['React','Next.js','Node.js','Express.js','Tailwind CSS','REST APIs','Socket.IO'],
 'Data & auth':['MongoDB','PostgreSQL','Supabase','Prisma','Firebase Authentication','JWT','Google Sign-In','Phone OTP','Resend'],
 'Tools':['Git','GitHub','VS Code','Vercel']
};
